### ISSUE TITLE
question about the result of demo_test.m

### ISSUE THREAD

**Issue by littlewhitesea** [XinyiYing/MOVIE#1]
Thank you for sharing the code of calculating the Video Quality Assessment metric. I have two questions about the result of the file 'demo_test.m'.

1. When I ran the file 'demo_test.m', the command window of Matlab showed that 'tool\ffmpeg.exe' is not internal or external command. I guess the path 'tool\.' may loss a file called 'ffmpeg.exe', so I put my file 'ffmpeg.exe' into the path 'tool\.', and then the code can normally run. I would like to know what I did is right?

2. The final result of demo_test.m is very small, such as Spatial MOVIE value = 0.0313006, Temporal MOVIE value = 0.0064241 and MOVIE value =0.00250876. I am not sure whether the value is right or not.

Hope you can help me solve the above mentioned questions.

**Comment by XinyiYing** [comment]
Thank you for following our code.
"ffmpeg.exe" is required for running this code and we point out this requirement in the folder "./tool/README.md”. You can download ffmpeg.exe in https://pan.baidu.com/s/1utk27rQiW5tHKSlnCajQLw/ or https://ffmpeg.zeranoe.com/builds/ and put the ffmpeg.exe in "./tool/ffmpeg.exe". We update "README.md" in the base folder to clarify this requirment.
The results of your MOVIE and T-MOVIE is right and we usually use the 10e3 * MOVIE and T-MOVIE as the final results to be shown.

**Comment by littlewhitesea** [comment]
Thanks for your detailed and quick reply.
